server.port=${PORT:8080}

spring.profiles.active=@springProfiles@
spring.jpa.open-in-view=false

# For properties defined with 
#    var=${SYMBOL:${env.SYMBOL}}
# the SYMBOL value on the left of the : is the value from env,
# and will pick up values from Heroku or Dokku Config Vars.
# The env.SYMBOL value on the right of the : is the value from a .env file
#   and is picked up as a result of this plugin in the pom.xml  
#     <groupId>me.paulschwarz</groupId>
#     <artifactId>spring-dotenv</artifactId>


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:${env.GOOGLE_CLIENT_ID:client_id_unset}}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:${env.GOOGLE_CLIENT_SECRET:client_secret_unset}}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

management.endpoints.web.exposure.include=mappings,health
springdoc.swagger-ui.csrf.enabled=true
spring.jpa.hibernate.ddl-auto=update
app.admin.emails=${ADMIN_EMAILS:${env.ADMIN_EMAILS:phtcon@ucsb.edu}}

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
server.compression.enabled=false

spring.mvc.format.date-time=iso

app.oauth.login=${OAUTH_LOGIN:${env.OAUTH_LOGIN:/oauth2/authorization/google}}

management.endpoints.access.default=none
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=always

app.public_key=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtk1+EPDKTELFDB6mEjg60YFRthcZUzm2l21NI+LYC\
  jHVCXcr/SeNmBgLnKqy9sr819NJIoOjbJot/G8YhN9Hr2SqTXq2k3B/oScJyg4FvtC2OiTCmjACafB6oHg4qzRoNR64ify7W7D\
  uunlNs08tGT0gA27FTlh2WM/nEEJ1Ikn/MvsoT14nY/J6SnTQSJXjZT4wnbXLxT/pXFTPRj1zVeRv6IcUpU9V7meKfwukz5fTL\
  YyB0+mE6knpJt9WsqFwe9/JFVPL4dwFUXmKS5rour+gjeG5BkChpVETuZokYb3VfkbiBI7d4L1FBQXa2sxkB+n7GA26sv09Fqp\
  khJV3Y9BHrwA0xOQ8KFYsJnpKhCGTX1EZl6biyMU/mhuItWpW3BL0129UmO0dmBRNrSEzkVq43xH0cqV6mGsIok4xS5BWLEkhl\
  /Wz7cqIizkDxNpd6EMZX9iJQtkb6aipANWgyEo/VH0nIDoqjEjNnxlZAouDcDykTITal9a8dbKrt85JfC5nbt0SUQmHu/fKNxt\
  yGT/23muk/XCqOI2EkjRWd+2At1gIG5X6PY3uvOGtx+6UBPm2mktB5bVKxQ6sc4HZXJD1CMg9Fx7IZA8cnCD/7llczYc0J+Qe\
  zQ7ve20kmg0XoO5C5bhbT5FTsuzffdYuYPI0a4XjOEUEDHAZHH75w08CAwEAAQ==